# Generated by Django 4.1.1 on 2022-09-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HackerNewApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="item_id",
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
