# Generated by Django 4.1.1 on 2022-09-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HackerNewApp", "0002_alter_news_item_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=35)),
                ("item_id", models.CharField(max_length=25)),
                ("text", models.TextField()),
                ("descendants", models.IntegerField()),
                ("kids", models.TextField()),
                ("score", models.IntegerField()),
                ("time", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=250)),
                (
                    "type_of",
                    models.CharField(
                        choices=[
                            ("story", "story"),
                            ("comment", "comment"),
                            ("ask", "ask"),
                            ("job", "job"),
                            ("poll", "poll"),
                            ("pollopt", "pollopt"),
                        ],
                        max_length=7,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=35)),
                ("item_id", models.CharField(max_length=25)),
                ("text", models.TextField()),
                ("kids", models.TextField()),
                ("parent", models.IntegerField()),
                ("time", models.CharField(max_length=40)),
                (
                    "type_of",
                    models.CharField(
                        choices=[
                            ("story", "story"),
                            ("comment", "comment"),
                            ("ask", "ask"),
                            ("job", "job"),
                            ("poll", "poll"),
                            ("pollopt", "pollopt"),
                        ],
                        max_length=7,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=35)),
                ("item_id", models.CharField(max_length=25)),
                ("text", models.TextField()),
                ("score", models.IntegerField()),
                ("time", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=250)),
                (
                    "type_of",
                    models.CharField(
                        choices=[
                            ("story", "story"),
                            ("comment", "comment"),
                            ("ask", "ask"),
                            ("job", "job"),
                            ("poll", "poll"),
                            ("pollopt", "pollopt"),
                        ],
                        max_length=7,
                    ),
                ),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=35)),
                ("item_id", models.CharField(max_length=25)),
                ("descendants", models.IntegerField()),
                ("kids", models.TextField()),
                ("parts", models.TextField()),
                ("score", models.IntegerField()),
                ("text", models.TextField()),
                ("time", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=250)),
                (
                    "type_of",
                    models.CharField(
                        choices=[
                            ("story", "story"),
                            ("comment", "comment"),
                            ("ask", "ask"),
                            ("job", "job"),
                            ("poll", "poll"),
                            ("pollopt", "pollopt"),
                        ],
                        max_length=7,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pollopt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=35)),
                ("item_id", models.CharField(max_length=25)),
                ("poll", models.IntegerField()),
                ("text", models.TextField()),
                ("score", models.IntegerField()),
                ("time", models.CharField(max_length=40)),
                (
                    "type_of",
                    models.CharField(
                        choices=[
                            ("story", "story"),
                            ("comment", "comment"),
                            ("ask", "ask"),
                            ("job", "job"),
                            ("poll", "poll"),
                            ("pollopt", "pollopt"),
                        ],
                        max_length=7,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=35)),
                ("item_id", models.CharField(max_length=25)),
                ("descendants", models.IntegerField()),
                ("kids", models.TextField()),
                ("score", models.IntegerField()),
                ("time", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=250)),
                (
                    "type_of",
                    models.CharField(
                        choices=[
                            ("story", "story"),
                            ("comment", "comment"),
                            ("ask", "ask"),
                            ("job", "job"),
                            ("poll", "poll"),
                            ("pollopt", "pollopt"),
                        ],
                        max_length=7,
                    ),
                ),
                ("url", models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name="news",
            name="author",
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="news",
            name="descendants",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="kids",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="parent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="parts",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="poll",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="time",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="title",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="type_of",
            field=models.CharField(
                choices=[
                    ("story", "story"),
                    ("comment", "comment"),
                    ("ask", "ask"),
                    ("job", "job"),
                    ("poll", "poll"),
                    ("pollopt", "pollopt"),
                ],
                default=1,
                max_length=7,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="news",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="item_id",
            field=models.CharField(max_length=25),
        ),
    ]
