# Generated by Django 4.1.1 on 2022-09-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HackerNewApp", "0005_alter_news_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="author",
            field=models.CharField(max_length=35, null=True),
        ),
    ]
