# Generated by Django 4.1.1 on 2022-09-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HackerNewApp", "0007_news_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="public",
            field=models.BooleanField(default=True),
        ),
    ]
